// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqitnzulchbdxftnovpf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xaXRuenVsY2hiZHhmdG5vdnBmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NjMyODQsImV4cCI6MjA2NDAzOTI4NH0.hpRPZua4X0NDMvRYSI-e7eNev7X94kzoDBvANhfgCvw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);